name: pimp

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pimp-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://pimp:pimp@db:5432/pimp
      - BETTER_AUTH_SECRET=uOvjw4vT+zn5XPTlI1AyIvax/4stsvubb9AT56SAoUQ=
      - BETTER_AUTH_URL=http://localhost:3000

  db:
    image: postgres:18-alpine3.23
    container_name: pimp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pimp
      POSTGRES_USER: pimp
      POSTGRES_PASSWORD: pimp
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pimp -d pimp']
      interval: 5s
      timeout: 5s
      retries: 5

  rustfs:
    image: rustfs/rustfs:latest
    container_name: pimp-storage
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - RUSTFS_ACCESS_KEY=pimp-dev-access-key
      - RUSTFS_SECRET_KEY=pimp-dev-secret-key
    volumes:
      - ./.data:/data

volumes:
  postgres_data:
  rustfs_data:

